### ISSUE TITLE
Battery compartment markings

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#104]
We can add a + and - sign to the inside
![img_20150407_174514](https://cloud.githubusercontent.com/assets/281642/7020814/9cb34e2c-dd4e-11e4-8045-7917d431d274.jpg)

**Comment by starno** [comment]
added the indicators 

![capture](https://cloud.githubusercontent.com/assets/352025/9149204/c9beaaf4-3dd1-11e5-91a4-89d4c2d44725.PNG)
