### ISSUE TITLE
Thermocouple slots

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#107]
I measure the thermocouple slots at about 1.5 mm:
![screen shot 2015-05-04 at 14 18 37](https://cloud.githubusercontent.com/assets/281642/7449422/859090d6-f268-11e4-8ead-9ff27b3d41b8.png)

This is probably a little too big. With the new PCB thermocouple connector a male thermocouple can flatly hit the tab while being inserted.
![capture2](https://cloud.githubusercontent.com/assets/352025/7448676/fb3ebb70-f252-11e4-9611-4bd0ac849135.PNG)

I believe the PCB connector is designed to accept thermocouple up to 1.1 mm, is a little larger than any thermocouple connector I've seen. I think we can close the slot a bit to prevent the male TC connector from hitting the tab and also protecting the PCB connector from being damaged by overly large male TC contacts.

**Comment by starno** [comment]
@charlespax is this issue still relevant with the latest connectors?

**Comment by charlespax** [comment]
I don't think it would be a problem, but I would like to tighten up that dimension to 1.3 mm with the bottom edge of the hole aligning with the inside bottom edge of the connector.
![screen shot 2015-08-08 at 13 52 48](https://cloud.githubusercontent.com/assets/281642/9149275/4bc8d4cc-3dd5-11e5-8dbb-b81409b1fe21.png)

**Comment by starno** [comment]
done. 

![capture](https://cloud.githubusercontent.com/assets/352025/9149383/e18f94f6-3dd9-11e5-9258-f1670f224d7e.PNG)
