### ISSUE TITLE
LCD cover files

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#109]
@starno please add a file suitable for laser cutting the LCD cover to the repo. I'll order samples for this next set of prototypes.

**Comment by starno** [comment]
added lasercut directory and dxf of window

**Comment by charlespax** [comment]
What's the thickness of that window?

**Comment by starno** [comment]
0.5mm

![capture](https://cloud.githubusercontent.com/assets/352025/9149717/1e9f75d2-3de9-11e5-9f97-fc26f5fae09b.PNG)

**Comment by charlespax** [comment]
Thanks. What is tolerance can we handle with that?

**Comment by starno** [comment]
+0 / -0.1mm I'd say.  Its going to cause trouble if its too thick, and I have never had sheet of material too thick, I think theyre always are thinner than advertised

**Comment by charlespax** [comment]
Cool. Thanks.
