### ISSUE TITLE
Thermocouple connector changes

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#110]
The factory had a few problems and I made changes to the thermocouple connector design to address their tolerances. Then entry bends are now 45 degrees and the connector gap is specified at 0.6 +/- 0.1 mm as seen in the image below. From testing their samples the connector should still be able to bend without permanently deforming. I will be at the factory during production to spot check connectors and try to keep the factory to a tighter tolerance.

The 3D model should reflect these changes.

![e76e7af6-ee8b-11e4-9c33-0d19a4eb6c7c](https://cloud.githubusercontent.com/assets/281642/9149431/37a75318-3ddc-11e5-98d2-caf536333e50.png)

**Comment by starno** [comment]
Ok, updated the CAD.  I like this change as it completely eliminates the concern with issue#107

 ![capture](https://cloud.githubusercontent.com/assets/352025/9149688/efdfbb0e-3de7-11e5-867d-194f9ca49348.PNG)

![capture2](https://cloud.githubusercontent.com/assets/352025/9149690/24d75074-3de8-11e5-84a3-6f7aface3a54.PNG)
