### ISSUE TITLE
SD card constraint

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#115]
As described in #96 the SD card can be lost int he enclosure. This is still true in the latest enclosure (0.5) design. The SD card can be inserted above the card slot.
![sd_above](https://cloud.githubusercontent.com/assets/281642/9272676/7725767a-42b7-11e5-916d-5eeafb0d2cf5.jpg)
![sd_below](https://cloud.githubusercontent.com/assets/281642/9272680/7eafa4a6-42b7-11e5-9d56-dcb636148686.jpg)

**Comment by starno** [comment]
Added a second rib above the slot so it shouldn't be possible to miss the connector anymore.  The bottom is already limited to where the existing rib is, but it's protecting that area just fine with the prototype 

![capture](https://cloud.githubusercontent.com/assets/352025/9322238/dd7c947e-45a2-11e5-8ebd-9832f2735a27.PNG)
