### ISSUE TITLE
Laser cut window misalignment

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#117]
The bottom edge of the laser cut window does not sit in the depression on the 0.5 SLA print. It works fine on the 0.4 print.

**Comment by charlespax** [comment]
Here you can see the overlap.
![window corner](https://cloud.githubusercontent.com/assets/281642/9272790/8273a546-42b8-11e5-9e3a-54975adc0458.jpg)

**Comment by starno** [comment]
turned out to be the vendor's mistake, as the modified window matches the CAD

**Comment by charlespax** [comment]
This was actually my mistake. I sent them an earlier file. I fixed this and all is well.
