### ISSUE TITLE
Front label depression size

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#118]
On the 0.5 SLA prints the from label depression may not be large enough. It seems fine on 0.4. Could be SLA dimensions are off or the sticker I have is larger than the previous one.

**Comment by charlespax** [comment]
Looking at the other prototypes it's also a little tight. Let's make it a little bigger. Maybe 0.4 or 0.5 mm larger on each side.
![Uploading IMG_20150814_184827.jpg…]()

**Comment by starno** [comment]
This breaks some of our early design and alignment rules, but the changes are in.  0.5mm border around sticker logo:
![capture2](https://cloud.githubusercontent.com/assets/352025/9322517/e4a66136-45a6-11e5-8dd3-20c3c16edfe5.PNG)
