### ISSUE TITLE
SD slot size

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#119]
Let's tighten up the SD card slot size.
![sd_face_no_card](https://cloud.githubusercontent.com/assets/281642/9272694/9ece9bca-42b7-11e5-84d9-79f3c3684fe2.jpg)
![sd_face_card](https://cloud.githubusercontent.com/assets/281642/9272695/9f0d5cf2-42b7-11e5-8489-07fd64be2606.jpg)

**Comment by starno** [comment]
tightened up the slot to be 0.3mm on top and bottom, 0.5mm on sides
![capture](https://cloud.githubusercontent.com/assets/352025/9322341/4e882c72-45a4-11e5-9a5d-c7b5e5a6b43c.PNG)
