### ISSUE TITLE
LCD bezel

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#120]
We should tighten up the bezel. The LCD is recessed a little, so a user is able to see the edges of the LCD.
![lcd_front](https://cloud.githubusercontent.com/assets/281642/9272843/06fdcf8a-42b9-11e5-9dcd-97e8881b8a49.jpg)
![lcd_left](https://cloud.githubusercontent.com/assets/281642/9272844/0704141c-42b9-11e5-9c9c-58e5c321bebe.jpg)
![lcd_right](https://cloud.githubusercontent.com/assets/281642/9272845/0736812c-42b9-11e5-98fc-69c8b0669c8a.jpg)

**Comment by starno** [comment]
bring in 1mm on each side

**Comment by starno** [comment]
brought in the bezel 1mm.  LCD border outline for reference:

![capture](https://cloud.githubusercontent.com/assets/352025/9322525/098c0000-45a7-11e5-8cfe-81a13b05dc52.PNG)
