### ISSUE TITLE
Threaded insert supports

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#122]
The threaded insert ont he battery cover is not held on by much. We should add some support ribs.
![threaded-insert](https://cloud.githubusercontent.com/assets/281642/9273177/9779abf8-42bc-11e5-86ab-1a8bca153dbe.jpg)

**Comment by starno** [comment]
added 3 ribs where there was room.  its possible to get a 4th rib if we move the thermocouple panel keyway to either side a few cm.  @charlespax what are your thoughts?

![capture](https://cloud.githubusercontent.com/assets/352025/9324248/173f143a-45bb-11e5-84b5-95ec486d5101.PNG)

**Comment by charlespax** [comment]
Moving the keyway is okay as long at is doesn't line up with a keyway on the front.

**Comment by starno** [comment]
4th rib added and keyway shifted over 12mm.
![capture](https://cloud.githubusercontent.com/assets/352025/9324542/1eaf88b4-45be-11e5-9a9e-bf4a878ecd48.PNG)

The slot never actually touches the battery cover every, so it can be anywhere on that side
![capture2](https://cloud.githubusercontent.com/assets/352025/9324573/6d2ccb3c-45be-11e5-8972-b57c3e4e6b13.PNG)
