### ISSUE TITLE
MicroUSB hole

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#123]
I'd like to tighten up the MicroUSB hold. I think that would improve the look.
![img_20150814_194935](https://cloud.githubusercontent.com/assets/281642/9273393/0eceff9e-42bf-11e5-9e5c-5d3893674e8a.jpg)

**Comment by starno** [comment]
I dont think we can get any tighter than we are at already because there are the tabs that flare out in all four directions.  @charlespax what exactly do you want to do here?

**Comment by charlespax** [comment]
What can you do to contour the hole around the connector shape? On the front piece it should be pretty easy to round off the corners. On the back piece we would have some sharp corners on the piece that sticks up.

We could change the shape of the hole a little, so there are no sharp corners. In the image below the yellow line shows the contour of the front and green shows the back. What do you think about this solution?

![0eceff9e-42bf-11e5-9e5c-5d3893674e8a](https://cloud.githubusercontent.com/assets/281642/9323939/5383b71e-45b8-11e5-9a51-dad9e87cd5a2.jpg)

**Comment by starno** [comment]
Looks good.  implementing...

**Comment by starno** [comment]
USB slot looks a lot less blocky now.  Same amount of clearance around connector except the overall shape of the hole resembles the connector better. 
![capture](https://cloud.githubusercontent.com/assets/352025/9348683/1b7f77bc-466d-11e5-8cae-d75873bd5025.PNG)

 I also changed the SD slot to be similar.  @charlespax what are your thoughts on the SD slot, better now or the way it was?

![Uploading Capture2.PNG…]()

**Comment by charlespax** [comment]
Looks really good in the first screenshot. The second one didn't upload, but I can see from the first one the SD slot looks good too.

**Comment by starno** [comment]
oops

![capture3](https://cloud.githubusercontent.com/assets/352025/9348766/2dd5a26e-466e-11e5-884a-9bef080d523b.PNG)

**Comment by charlespax** [comment]
Yeah, looks good :-)
