### ISSUE TITLE
MicroSD slot edges

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#126]
In commit 73edde1ac90ea6bb947693806ebfc6a88ce5d0d4 the SD card slot look really good. The corner on the back edge seems like it has a large radius. How do you feel about squaring it off a bit to have the same radius as the inside corner of the front?

![screen shot 2015-08-26 at 20 30 07](https://cloud.githubusercontent.com/assets/281642/9493359/82fec356-4c31-11e5-917c-b1470a13113e.png)

**Comment by starno** [comment]
I agree with you, it looks a bit off.  I could have sworn it was concentric already...

**Comment by starno** [comment]
fixed.
![capture2](https://cloud.githubusercontent.com/assets/352025/9517889/8575fcd0-4ce5-11e5-81cb-06f84f18deb7.PNG)
