### ISSUE TITLE
Tiny sliver edge

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#127]
From commit 73edde1ac90ea6bb947693806ebfc6a88ce5d0d4, would this sliver cause any problems for the tooling?

This is the battery cover.
![screen shot 2015-08-26 at 20 41 29](https://cloud.githubusercontent.com/assets/281642/9493563/fc4a6db8-4c32-11e5-81a5-ec5889cfe1e9.png)

Maybe this tiny feature on the tip can't be machined the way it is modeled.
![screen shot 2015-08-26 at 20 43 06](https://cloud.githubusercontent.com/assets/281642/9493590/2b57c5ce-4c33-11e5-8a3f-a7e57b786e3e.png)

**Comment by charlespax** [comment]
I think issues like this would be brought up when the factory evaluates the design. This should not hold up the 0.6 SLA print. Moving to production milestone.

**Comment by charlespax** [comment]
There are other similarly thin features on the battery cover.

![screen shot 2015-08-26 at 20 53 30](https://cloud.githubusercontent.com/assets/281642/9493752/8669387a-4c34-11e5-9e9b-9d25d19d6de9.png)

**Comment by starno** [comment]
at the moment there are a few areas with small features like this.  They are needed to satisfy the draft angles and pull directions.  We can work with the tooling house to optimize where the parting line is and how to minimize the appearance

**Comment by charlespax** [comment]
No issue form factory.
