### ISSUE TITLE
Bail-battery cover contact

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#128]
In commit 73edde1ac90ea6bb947693806ebfc6a88ce5d0d4 the tilting bail looks to have pretty good contact with the battery cover. Is this what we had in the previous version or did you beef this up?

![screen shot 2015-08-26 at 20 55 33](https://cloud.githubusercontent.com/assets/281642/9493800/d31f23b4-4c34-11e5-951d-e49cc373641e.png)

**Comment by charlespax** [comment]
This is different.

**Comment by starno** [comment]
yeah, this is beefed up so that it cant overshoot the stop like it did on the last prototype, both locking positions are controlled by the wings
