### ISSUE TITLE
Tilting bail wear area

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#129]
The alternate tilting bail looks pretty good. The feature that keep the bail open and the feature that keep the bail closed will wear on the same area of the tilting bail.
![screen shot 2015-08-27 at 13 23 40](https://cloud.githubusercontent.com/assets/281642/9514108/ad1eccec-4cc9-11e5-9131-f55bfd33f874.png)

If the ribs can be moved off to the side, the two features will wear the tilting bail in different spots. I don't know how significant this will be, but it would be worth doing if moving the features does not cause any problems.
![screen shot 2015-08-27 at 13 23 40 copy](https://cloud.githubusercontent.com/assets/281642/9514114/ba670b1c-4cc9-11e5-9691-9f31b73b4c56.png)

**Comment by starno** [comment]
great idea

**Comment by starno** [comment]
locking open and locking closed now touch the bail in different areas

![capture](https://cloud.githubusercontent.com/assets/352025/9517834/29b6abd8-4ce5-11e5-9d91-61b5778c18f8.PNG)
