### ISSUE TITLE
Should the TC number be embossed or debossed?

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#16]
Will this matter for manufacturing? Which one will look better? Do we have example from other products from which we can take inspiration?

![screen shot 2014-12-11 at 13 40 20](https://cloud.githubusercontent.com/assets/281642/5389646/54f79c24-813b-11e4-8893-99b25c2a2ad2.png)

**Comment by starno** [comment]
There are multiple places with debossing on this enclosure and it generally seems beneficial for our application.  Im going to close this issue
