### ISSUE TITLE
Top panel design

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#19]
We have the option to put some useful information onto the top panel. Maybe marking the positive and negative ends of the connectors.

![screen shot 2014-12-11 at 13 49 35](https://cloud.githubusercontent.com/assets/281642/5389736/9652b838-813c-11e4-94ea-cb6cdf6c7a55.png)

This is the Fluke 54 II B. I like the safety warning.
![img_20141211_134911](https://cloud.githubusercontent.com/assets/281642/5389778/5f9d4924-813d-11e4-9040-bb536c69dc0e.jpg)

**Comment by starno** [comment]
Any more details to add here before closing the issue?  The only thing that has changed from the last photo is that the positive and negative holes are different sizes to prevent backwards insertion

**Comment by charlespax** [comment]
Can you do a quick test with a thermocouple connector to verify it can't be plugged in backwards? I think I tested that, but can't remember. If we're good there, we can close it.

**Comment by starno** [comment]
Yeah, it checks out
