### ISSUE TITLE
Gap between PCB and enclosure

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#22]
It would be good to have a larger gap between the PCB and enclosure, so the enclosure can be used with a double sided design.

![screen shot 2014-12-11 at 14 06 09](https://cloud.githubusercontent.com/assets/281642/5389903/eda50f62-813e-11e4-9bb0-64c4f9aac3af.png)

**Comment by starno** [comment]
@charlespax can you give me the height and width of the new connector?  The height of the leaf spring contacts too.

**Comment by charlespax** [comment]
Height: 6.86 mm. Width: 9.52 mm (should be the same). Leaf spring contact height: .74 mm.

**Comment by starno** [comment]
it seems the numbers on the connector represent the height. 6 8 for 6.8mm and 7 7 for 7.7mm

**Comment by starno** [comment]
2mm all over the backside 

![capture2](https://cloud.githubusercontent.com/assets/352025/5970980/d8e0884a-a876-11e4-9fe8-cd9f2e11e90b.PNG)
