### ISSUE TITLE
Battery information

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#24]
Maybe have something in this area indicating what type of battery the device takes.
![screen shot 2014-12-11 at 14 16 30](https://cloud.githubusercontent.com/assets/281642/5390099/63390750-8140-11e4-88b7-5354cf459f33.png)

**Comment by charlespax** [comment]
Probably just BL-5C.

**Comment by starno** [comment]
This is what the battery info looks like

![capture](https://cloud.githubusercontent.com/assets/352025/5771644/2bbb4498-9d7c-11e4-8bfa-61c6b073ab3c.PNG)

**Comment by charlespax** [comment]
Looks good to me.
