### ISSUE TITLE
Battery cover gap

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#32]
In the Enclosure version 0.1 (SLA) print there is a fairly large gap between the battery cover and the back of the enclosure. When the battery cover is pushed into the upper left corner...
![img_20141218_122335](https://cloud.githubusercontent.com/assets/281642/5500264/ba6cf09a-877b-11e4-89e6-1dda6d2531b3.jpg)
we get this gap in the bottom right.
![img_20141218_122322](https://cloud.githubusercontent.com/assets/281642/5500265/bc3507be-877b-11e4-939f-d29ccd3c0e99.jpg)

**Comment by starno** [comment]
Gap closed to 0.19mm down from 0.5mm.  It should feel pretty snug

![Uploading Capture.PNG . . .]()
