### ISSUE TITLE
Battery notch

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#33]
In the Enclosure version 0.1 (SLA) print the space the battery slides into seems too small. When installing the battery I need to wedge the battery between the notch and enclosure. The image below shows the area I'm talking about. I don't know if this is the model or the print. I believe the battery should go in more smoothly.
![img_20141218_122813](https://cloud.githubusercontent.com/assets/281642/5500316/dfe48242-877c-11e4-8b1c-6fd9ba364917.jpg)

**Comment by starno** [comment]
Turns out there wasn't any clearance between these two surfaces which explains why it was tight.  Clearance added.

![capture](https://cloud.githubusercontent.com/assets/352025/5772547/6c76d6c4-9d8f-11e4-85c8-4ac90e8d3ec6.PNG)
