### ISSUE TITLE
Top panel PCB support

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#35]
The slots for the top panel can probably be a bit smaller. The image below shows the gap when a 1.6 mm PCB is in the slot. We want the enclosure to support using custom PCBs for the top panel, which is true for the current design, but be a little less floppy. However, we should not compromise the enclosure integrity just to make a PCB top panel a bit less floppy.

Is there a technical reason for having the top panel be a thick as it is or can that be a bit smaller?

![img_20141218_123232](https://cloud.githubusercontent.com/assets/281642/5500373/1ee68fe8-877e-11e4-8075-d56632bd19db.jpg)

**Comment by starno** [comment]
This is fixed with along with issue #34
