### ISSUE TITLE
SLA print strangeness

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#36]
The Enclosure version 0.1 (SLA) print has a strange feature on it. The area shown in the image below seems to be made of two polygons that are not coplanar. I can feel the difference when I touch it. There is nothing strange in the model though.
![img_20141218_123457](https://cloud.githubusercontent.com/assets/281642/5500422/1db5d43e-877f-11e4-9494-10ab014c3592.jpg)
![screen shot 2014-12-19 at 13 00 12](https://cloud.githubusercontent.com/assets/281642/5500423/1f3868da-877f-11e4-92ed-e29f2cecba77.png)

**Comment by starno** [comment]
That is strange.  Might be an STL artifact.  Since there is nothing that needs to be changed, Im going to close this
