### ISSUE TITLE
Threaded insert geometry

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#39]
In the Enclosure version 0.1 (SLA) print the holes for the threaded inserts to not match the threaded inserts I have. I have not tested with the new threaded inserts, so there is no indication of a problem. I just want to give a sense of the size and bring attention to an inconsistency: the geometry for the enclosure threaded inserts and the one battery cover insert do not match.

Here is one of the four enclosure standoffs. You can see the threaded insert rests right inside the hole.
![img_20141218_123736](https://cloud.githubusercontent.com/assets/281642/5500534/396f3416-8781-11e4-961e-3069a2969682.jpg)

For the battery cover, however, the threaded insert does not fit at all.
![img_20141218_123817](https://cloud.githubusercontent.com/assets/281642/5500535/3be3c996-8781-11e4-87cc-3b4e0d570c88.jpg)

 I tried to widen the hole then push the threaded insert in with a soldering iron. Whoops!
![img_20141218_124906](https://cloud.githubusercontent.com/assets/281642/5500546/7b56cbdc-8781-11e4-953e-6a0e55538612.jpg)

**Comment by charlespax** [comment]
@starno is this resolved?

**Comment by starno** [comment]
This is resolved.  All the threaded insert locations are made to fit the M2 3.2x5mm inserts
