### ISSUE TITLE
Tilting bail size mismatch

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#42]
When putting together the Enclosure version 0.1 (SLA) print I was unable to put on the tilting bail. Upon closer inspection I noticed that the hinge was larger than the space it has to pass through. Looking at the model I see that I have to pass a 6.51 mm hinge through a 6.32 mm space. I cut off the protrusion to assemble the print, but this should be fixed.

![img_20141218_123945](https://cloud.githubusercontent.com/assets/281642/5500633/9692ee92-8783-11e4-8615-58d62b42f6d0.jpg)
![screen shot 2014-12-19 at 13 32 22](https://cloud.githubusercontent.com/assets/281642/5500631/8d741e8a-8783-11e4-81f2-a6c3542c2887.png)
![screen shot 2014-12-19 at 13 30 50](https://cloud.githubusercontent.com/assets/281642/5500632/8ee347f0-8783-11e4-9217-59abf3f78d82.png)

**Comment by starno** [comment]
The new bail design avoids this problem all together
