### ISSUE TITLE
Enclosure version 0.1 (SLA) results

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#44]
The Enclosure version 0.1 (SLA) prints look pretty good. There are few issues that may be due to the printing or the model. These are mentioned in other Github issues. Below is a series of photographs of the Enclosure version 0.1 (SLA) prints.

(The buttons are inset because the PCB does not have switches installed.)
![img_20141219_103727](https://cloud.githubusercontent.com/assets/281642/5517297/a25cc90c-8916-11e4-8ae0-53600a1ae37a.jpg)

Front exterior
![img_20141218_124217](https://cloud.githubusercontent.com/assets/281642/5517276/f5a0bbc4-8915-11e4-953a-cd4ecdc0a50e.jpg)

Front interior
![img_20141218_124222](https://cloud.githubusercontent.com/assets/281642/5517277/018d6ff4-8916-11e4-8978-75251916f667.jpg)

Back exterior
![img_20141218_124146](https://cloud.githubusercontent.com/assets/281642/5517323/1450d1aa-8919-11e4-91c9-28840c3a790f.jpg)

Back interior
![img_20141218_124153](https://cloud.githubusercontent.com/assets/281642/5517321/0c0f0296-8919-11e4-8a0d-6a53c5416467.jpg)

Top panel exterior (circle is reference to https://github.com/PaxInstruments/t400-enclosure/issues/43)
![img_20141218_124236](https://cloud.githubusercontent.com/assets/281642/5517280/2689abd8-8916-11e4-9bfd-79bd974c1697.jpg)

Top panel interior
![img_20141218_124244](https://cloud.githubusercontent.com/assets/281642/5517282/3aa40b04-8916-11e4-9186-90c2ef2fbc0d.jpg)

Battery cover exterior
![616bc998-8916-11e4-8dcc-1f1be610b9d0](https://cloud.githubusercontent.com/assets/281642/5517332/aac35b58-8919-11e4-94c8-04edc1823d05.jpg)

Battery cover interior
![699309d8-8916-11e4-9dc9-a3c8900af9c2](https://cloud.githubusercontent.com/assets/281642/5517333/abdf398a-8919-11e4-97fb-b1679bb0a339.jpg)

Tilting bail exterior
![7e85aad0-8916-11e4-8794-1f225d920e49](https://cloud.githubusercontent.com/assets/281642/5517338/b6b9c9d8-8919-11e4-8651-760b0d74be8f.jpg)

Tilting bail interior
![8559c3dc-8916-11e4-86c4-1d1f63175e36](https://cloud.githubusercontent.com/assets/281642/5517336/b16a0858-8919-11e4-83a4-ee1cf0f257e4.jpg)

Keypad
![img_20141218_124251](https://cloud.githubusercontent.com/assets/281642/5517284/576d0862-8916-11e4-8074-e8638268dbc1.jpg)

Here is how the tilting bail and battery cover match up
![img_20141218_124015](https://cloud.githubusercontent.com/assets/281642/5517364/5c29e2ee-891b-11e4-9f9c-de1af17c31e9.jpg)

After modification (https://github.com/PaxInstruments/t400-enclosure/issues/42) they snap together
![img_20141218_125447](https://cloud.githubusercontent.com/assets/281642/5517368/7d962cbc-891b-11e4-827b-14bec7a0803a.jpg)

**Comment by starno** [comment]
looks good, but 0.2 will be better
