### ISSUE TITLE
Tilt angle

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#46]
In the Enclosure version 0.1 (SLA) print the tile angle is a bit shallow. I would like the the T400 to tilt bacl a bit more.

![img_20141218_130212](https://cloud.githubusercontent.com/assets/281642/5517341/09ec9f68-891a-11e4-917d-f1b63786c912.jpg)

It would be good to match the tilt angle and bail angle of this other device.
![img_20141218_131033](https://cloud.githubusercontent.com/assets/281642/5517342/0dbd646a-891a-11e4-8e4b-f0cf9f9e37d4.jpg)

**Comment by starno** [comment]
Tilt angle is open another 10deg, currently at 70deg.
![angle](https://cloud.githubusercontent.com/assets/352025/5886825/b72fe8c8-a3ec-11e4-8c27-40debe0f73cd.PNG)
