### ISSUE TITLE
Tilting bail finger slot

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#47]
In the Enclosure version 0.1 (SLA) print the tilting bail finger slot is a bit small. It is difficult to get my index finger and thumb in the slot.

Index finger
![img_20141218_125648](https://cloud.githubusercontent.com/assets/281642/5517353/6d11fcdc-891a-11e4-8fa8-03eda8460875.jpg)

Thumb
![img_20141218_125709](https://cloud.githubusercontent.com/assets/281642/5517354/6dfb56c0-891a-11e4-933b-a84fdeb57087.jpg)

The slot in the bail can be made larger
![b6b9c9d8-8919-11e4-8651-760b0d74be8f](https://cloud.githubusercontent.com/assets/281642/5517359/058d9d68-891b-11e4-8c63-fd0fe45067aa.jpg)

or we can remove some material from the back of the enclosure
![1450d1aa-8919-11e4-91c9-28840c3a790f](https://cloud.githubusercontent.com/assets/281642/5517361/134a2296-891b-11e4-96b0-bd01aa741a5b.jpg)

**Comment by starno** [comment]
The new bail files have bigger opening that fits fingers much better

![capture](https://cloud.githubusercontent.com/assets/352025/5776051/6a438090-9dbd-11e4-8e6d-3d626c8c8dfa.PNG)

**Comment by charlespax** [comment]
Nice!
