### ISSUE TITLE
Tilting bail snap

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#48]
In the Enclosure version 0.1 (SLA) print I cannot snap closed the tilting bail. The bail just flexes. I have to press on both sides for it to snap. This is probably just due to the printing material. For the mold we should probably make the snap numbs a little smaller. Then we can always remove mold material and make them longer to get the right snap.
![img_20141218_125726](https://cloud.githubusercontent.com/assets/281642/5517372/abb6aa9a-891b-11e4-85ef-479496273539.jpg)

**Comment by starno** [comment]
The new bail approach bypasses this problem all together.  We shouldnt have to worry about this anymore.
