### ISSUE TITLE
Window tabs

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#50]
To help secure the window we can add tabs that slot into the areas indicated below. This could be a good spot to to sonic or heat welding to the enclosure. However, adding tabs to the otherwise rectangular window would make manufacturing that part more complex and thus costly.

![screen shot 2014-12-21 at 14 24 23](https://cloud.githubusercontent.com/assets/281642/5517404/19042fcc-891d-11e4-9e07-2d6f58367bd2.png)

![img_20141218_130805](https://cloud.githubusercontent.com/assets/281642/5517403/f73daeea-891c-11e4-840e-4d408e75d95e.jpg)

**Comment by starno** [comment]
This was addressed in commit 6e667a0220e7789e9d8e74c5966f5af1079e687e.  There are 4 locations on the sides for the melt rivets, and the top and bottom of the window can either rely on the compression of LCD against the front when it is assembled or use a strip adhesive to attach it to the front.
![window](https://cloud.githubusercontent.com/assets/352025/5855906/6bb9a692-a278-11e4-9493-aff33acab267.PNG)

**Comment by charlespax** [comment]
That looks really good. Let's close this issue.
