### ISSUE TITLE
MicroSD card slot model

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#53]
We have moved to a new MicroSd card slot. The model in the enclosure is the old one. The model should also reflect how far the card slot should hang over the edge. See https://github.com/PaxInstruments/t400-electronics/issues/79

![screen shot 2014-12-21 at 14 53 52](https://cloud.githubusercontent.com/assets/281642/5517491/d5500288-8921-11e4-9e2c-0b912b3f357b.png)
![screen shot 2014-12-21 at 14 57 03](https://cloud.githubusercontent.com/assets/281642/5517492/d5d3f26e-8921-11e4-9d1d-bc34743a3be3.png)

**Comment by starno** [comment]
Connector is now at 0.7mm from PCB edge to add more clearance from inside wall while also not protruding beyond the enclosure when sd is in the locked position.

**Comment by charlespax** [comment]
Please add a screen shot.

**Comment by starno** [comment]
From PaxInstruments/t400-electronics#79
![](https://cloud.githubusercontent.com/assets/352025/5598906/f43b4744-92f8-11e4-9a61-00a4b07609a6.png)

**Comment by charlespax** [comment]
Cool. Thanks :-)
