### ISSUE TITLE
SD card during assembly

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#54]
A MicroSD card will be inserted into each T400 during the PCBA process for testing. This will be the SD card that ships with the device. Therefore the enclosure should be capable of being assembled while the MicroSD card is installed in the device.

In this screen shot this looks like it will not be a problem. I need to pick up an SD card to confirm this.
![screen shot 2014-12-23 at 11 45 26](https://cloud.githubusercontent.com/assets/281642/5534374/6776031a-8a99-11e4-8ed1-4287f07f5368.png)

**Comment by starno** [comment]
This does not appear to interfere at all with assembly.  SD lines up nicely in prototype with no interference

![capture](https://cloud.githubusercontent.com/assets/352025/5886836/5c057dfe-a3ed-11e4-9eb1-aaf9bc73ac50.PNG)
