### ISSUE TITLE
Silicone keypad height

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#55]
In the Enclosure version 0.1 (SLA) print the keypad buttons are only slightly above the enclosure surface. Looking at it, I'm not sure if they are tall enough. This is something we should test once we have an Electronics version 0.9 PCB. Let's make this something address in Enclosure version 0.2 (SLA) if necessary.
![img_20141223_114911](https://cloud.githubusercontent.com/assets/281642/5534401/a418af88-8a9a-11e4-843d-a55c6f96e822.jpg)

**Comment by starno** [comment]
The buttons currently sit 0.5mm above the front surface of the enclosure.  Now the silicone sits directly on the mechanical buttons, so it doesnt have room to fall back into the case anymore.  Do you think this is tall enough?

![capture](https://cloud.githubusercontent.com/assets/352025/5886947/a1b88770-a3f1-11e4-91f7-d95b5b123cb2.PNG)

**Comment by charlespax** [comment]
I think we'll have to do something more like 1.5 mm. In Enclosure version 0.2 (SLA) let's get several button lengths. We should try 0.5 mm, 1.0 mm, and 1.5 mm above the enclosure surface.

**Comment by starno** [comment]
Ok, I have an STL of each size to get made.  The current model is defaulted to 1.5mm

![button height](https://cloud.githubusercontent.com/assets/352025/5896016/aba85882-a568-11e4-849f-c147b39014ce.PNG)
