### ISSUE TITLE
Battery compartment interior thickness

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#56]
The enclosure shell is 2 mm thick all round. The interior of the battery compartment is also 2 mm thick. Can the wall thickness within the battery compartment be reduced without noticeably affecting the strength of the case?

If we can reduce this thickness, we will gain some space above the PCB without increasing the size of the enclosure.

![screen shot 2014-12-25 at 19 20 05](https://cloud.githubusercontent.com/assets/281642/5553828/a44545a2-8c6b-11e4-9957-c956f369558d.png)
![screen shot 2014-12-25 at 19 19 43](https://cloud.githubusercontent.com/assets/281642/5553829/a49a6aa0-8c6b-11e4-8695-190ec67a39f5.png)

**Comment by starno** [comment]
The surface under the battery is thinner than the rest of the part.  Might cause blemishes, but it's pretty well hidden

![capture](https://cloud.githubusercontent.com/assets/352025/5970966/73b9ba9a-a876-11e4-9eac-f36987707689.PNG)
