### ISSUE TITLE
Injection molded windown

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#57]
Right now we're using cut plastic sheet for the window. It may even be die cut with rivet holes (https://github.com/PaxInstruments/t400-enclosure/issues/50). It would be good to have an enclosure design that would allow an injection molded window in the future.

**Comment by starno** [comment]
The most current solution can be lasercut or injection molded as is.
![window](https://cloud.githubusercontent.com/assets/352025/5857008/2883e648-a283-11e4-873b-9a3eda5a95ae.PNG)
