### ISSUE TITLE
Pax Instruments logo on enclosure front

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#59]
If we reduce the window chamfer (https://github.com/PaxInstruments/t400-enclosure/issues/58), we can get a logo on the front. It would be cool to have it molded into the case and maybe heat stamped. 
![screen shot 2014-12-27 at 00 47 22](https://cloud.githubusercontent.com/assets/281642/5558419/1b8b87ba-8d62-11e4-87ed-4d65db7d0165.png)

**Comment by starno** [comment]
Can you send me vector logo for this?

**Comment by charlespax** [comment]
I've uploaded graphics to t400-enclosure/graphics.

**Comment by charlespax** [comment]
Moving this to Enclosure version 0.2 (SLA).

**Comment by starno** [comment]
Logo'd

![capture](https://cloud.githubusercontent.com/assets/352025/5871990/ae0be246-a320-11e4-9e9f-15aa6eba8a3d.PNG)
![capture2](https://cloud.githubusercontent.com/assets/352025/5871991/b03bbb72-a320-11e4-8030-deb1697aa3ec.PNG)

**Comment by charlespax** [comment]
Looks good :-)
