### ISSUE TITLE
High-Cycle, Longer-Life Bail Design!!!

### ISSUE THREAD

**Issue by starno** [PaxInstruments/t400-enclosure#60]
Here's an idea for an alternative approach at the bail/battery cover pair.  I think this is more promising for repeated cycles, and maintains the lock-open and lock-closed requirements.  It also can be made with a single-pull mold.

It works by having a flexible "wing" on the bail with a boss on the end:
![screen shot 2015-01-03 at 7 10 30 am](https://cloud.githubusercontent.com/assets/352025/5600568/a5c853a8-9317-11e4-97a8-48043f844bea.png)
There are corresponding holes on the battery cover to control it's position.

In the closed position:
![screen shot 2015-01-03 at 6 59 07 am](https://cloud.githubusercontent.com/assets/352025/5600582/f4430a00-9317-11e4-9d43-b98d5946250b.png)

As it opens, the wing flexes against the wall and creates resistance:
![screen shot 2015-01-03 at 7 00 05 am](https://cloud.githubusercontent.com/assets/352025/5600590/15d13a7a-9318-11e4-979d-7246ab31abe3.png)

In the open position a notch on the battery cover wall allows the wing to return to its natural position, and prevents the bail from closing without user pushing on it:
![screen shot 2015-01-03 at 7 00 55 am](https://cloud.githubusercontent.com/assets/352025/5600606/9b066d46-9318-11e4-968a-6717d135c3e1.png)

If the bail is opened beyond its natural open position, it stops against the wall like the current bail:
![screen shot 2015-01-03 at 7 02 04 am](https://cloud.githubusercontent.com/assets/352025/5600620/249ca2fa-9319-11e4-9729-413a08b4e85f.png)

Thoughts?

**Comment by charlespax** [comment]
Looks good. With the right hold placement the bail should feel really solid.

How do you feel about getting some parts machined to try this out? We would need the battery cover, bail, and part of the enclosure back. We just need enough to test this with actual ABS. Better to test the mechanism early than to spend time fully implementing it only to find we don't like it.

**Comment by starno** [comment]
I feel good about it.  CNCd out of ABS should be really telling for how well it will work.  This has been merged into the original files and replaced the old bail in all the CAD master files.

**Comment by charlespax** [comment]
Do we need any chamfer on the highlighted edges?
![screen shot 2015-01-22 at 12 37 30](https://cloud.githubusercontent.com/assets/281642/5850598/8187adb0-a233-11e4-9af2-0e325bbd5016.png)

**Comment by starno** [comment]
The bail and battery cover assembly had a lot of refinements in 49284562307c798eb90a043f63ebbd4d5f7dcef9

Those particular edges have a drafted surface that acts like a chamfer.
![Uploading Capture.PNG . . .]()
