### ISSUE TITLE
MicroUSB port squishes keypad

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#62]
I put the Electronics version 0.9 PCBA in the Enclosure version 0.1 (SLA) print. In the image below you can see how the MicroUSB connector pressed directly against the keypad. Since the keypad in this print is hard SLA material, the buttons do not work. This may not be an issue in the silicone keypad.

![screen shot 2015-01-03 at 20 45 34](https://cloud.githubusercontent.com/assets/281642/5602460/8b1326b0-9389-11e4-95a8-b828cca1bd0c.png)

**Comment by starno** [comment]
As of now the buttons and connector are the same height, so it might affect the feel of 2/3 buttons on that side.  One option is to get taller buttons and a make a corresponding indent in the silicone to accommodate.  @charlespax  @samchoy88 Do we have a final button configuration/part number chosen already?

**Comment by charlespax** [comment]
Here is a switch with a taller button. The height from PCB is 3.63 mm unpressed and 3.43 mm when pressed.

![img_20150122_122727](https://cloud.githubusercontent.com/assets/281642/5850540/6f557e20-a232-11e4-9756-e60370d4436c.jpg)
![img_20150122_122753](https://cloud.githubusercontent.com/assets/281642/5850541/6f5af4b8-a232-11e4-87ba-0bffb8ce523f.jpg)
![img_20150122_122640](https://cloud.githubusercontent.com/assets/281642/5850542/6f69083c-a232-11e4-9edf-e2ccc6c631d6.jpg)

**Comment by starno** [comment]
Ok, thanks.  That's going to interfere with the silicone buttons so I will add a recess
![capture8](https://cloud.githubusercontent.com/assets/352025/5850820/3a00b906-a237-11e4-942f-9f36e2eafd51.PNG)

**Comment by charlespax** [comment]
Will the distance between the keypad bottom and the microUSB connector increase? If not, I think we'll still have the squishing issue.

![screen shot 2015-01-22 at 13 09 01](https://cloud.githubusercontent.com/assets/281642/5850859/e360075e-a237-11e4-84b8-794d3314fa68.png)

**Comment by starno** [comment]
It did not increase but is able to.  I don't think the squishing issue will still be there because the silicone rests directly on the buttons and will be depressed before there is any contact with the usb connector.
![buttons](https://cloud.githubusercontent.com/assets/352025/5856912/2d846434-a282-11e4-9f7f-217daa3a9f6e.PNG)

**Comment by charlespax** [comment]
I think the USB connector model may not be accurate. The gap that exists in the assembly did not appear to exist in the prototype. Can you physically verify there is a gap I. The prototype you have?

**Comment by starno** [comment]
Good call, there was some interference there

there should be plenty of clearance there now
![capture](https://cloud.githubusercontent.com/assets/352025/5869264/5db14630-a2f1-11e4-8dae-6d8a62bce8f8.PNG)
