### ISSUE TITLE
Fastening PCB

### ISSUE THREAD

**Issue by starno** [PaxInstruments/t400-enclosure#64]
Based on a discussion with @charlespax we decided to put the pcb onto bosses with a shoulder, the boss  passes through the PCB and the corresponding boss on from the back will meet up with it and keep everything constrained.

unfortunately a problem arises:
![capture2](https://cloud.githubusercontent.com/assets/352025/5787397/8e8751f0-9e37-11e4-9b45-8dbe6b1ebd8a.PNG)
The front panel bosses are larger than the back because they need to contain the threaded inserts.  This makes the hole in the PCB larger and the back panel boss diameter is not large enough to prevent any unwanted movement of the PCB.  We either have to reconsider the assembly operation (since having shoulder bosses on the back panel solves the issue) or use the pinching method like before.

Thoughts?

**Comment by charlespax** [comment]
I think shoulder bosses on the back is better than no shoulder. I don't think it would affect the assembly process since the LCD is already putting the PCB in the right place.

**Comment by starno** [comment]
I agree.  I also did a test run of the assembly with the prototype models and if the fit is tight on the PCB putting the back on with the PCB on it doesn't make a huge difference.  Either way I'll switch up the configuration

**Comment by charlespax** [comment]
Cool.

**Comment by starno** [comment]
This was fixed in commit bc3faf97fd03e1f0dbca54480562c21bee565d81
![capture](https://cloud.githubusercontent.com/assets/352025/5849625/01348cb0-a223-11e4-9758-c9283dda9a43.PNG)

**Comment by charlespax** [comment]
The PCB mounting holes need to be changed, issue opened (https://github.com/PaxInstruments/t400-electronics/issues/139).

@starno please comment on the issue (https://github.com/PaxInstruments/t400-electronics/issues/139) with the new hole dimensions.
