### ISSUE TITLE
Tilting bail lateral movement

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#65]
It looks like the bail will be able to move left and right quite a bit. It even looks like the small nubs that hold the bail open or closed will disengage completely if the bail is moved to one side.

![screen shot 2015-01-22 at 12 40 06](https://cloud.githubusercontent.com/assets/281642/5850618/e596f0d6-a233-11e4-8011-cb8cad9d6497.png)

Should the two surfaces marked in yellow mate?
![screen shot 2015-01-22 at 12 40 06](https://cloud.githubusercontent.com/assets/281642/5850640/4d462594-a234-11e4-80f9-c7c1c649b643.png)

**Comment by charlespax** [comment]
@starno what do you think?

**Comment by starno** [comment]
No, I don't think they should mate.  The bail and battery cover still need finishing touches.  will report back

**Comment by starno** [comment]
Ok, have a look at the files from 49284562307c798eb90a043f63ebbd4d5f7dcef9

Lateral movement is protected by the non-nub sides of the hinge in the center of the bail.  The length of both the axle boss and the locking wing boss both increased for strength and preventing accidental removal.
![capture](https://cloud.githubusercontent.com/assets/352025/5886874/3c40bcca-a3ef-11e4-9e18-82d4056c22e8.PNG)

**Comment by charlespax** [comment]
Cool. Looks like 0.26 mm. Let's close this out and readdress if the Enclosure version 0.2 (SLA) prototype has any problems.
![screen shot 2015-01-25 at 13 58 37](https://cloud.githubusercontent.com/assets/281642/5890520/4f52e6d4-a49a-11e4-9283-89b3fd41c427.png)
