### ISSUE TITLE
Tilting bail flexing

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#66]
When the tilting bail is snapped into the battery cover the tilting bail must flex. Are the cutouts long enough to allow this?

![screen shot 2015-01-22 at 12 41 11](https://cloud.githubusercontent.com/assets/281642/5850643/625daa24-a234-11e4-9b0b-015b35ecb7ce.png)

**Comment by starno** [comment]
so the thought here is that the cutout length needs to be on the shorter side of acceptable for two reasons:  it's a one-time snap; it must be harder to flex than the "wing" to avoid the bail from displacing or falling out when trying to open or close the bail.  The cnc parts will be telling.  Do you want to start longer than it is?

**Comment by charlespax** [comment]
For the cutout length we should just machine what you have here. We can always hacksaw it longer to find the perfect length. However, the cutout width may not be enough. The cutout width is 1 mm. The nub is engaging with the battery cover 1 mm. It would be bad if the flexing part bottoms out before the nub disengages from the battery cover.

**Comment by charlespax** [comment]
@starno can you do some measurements or FEA to see if what you have will work?

**Comment by starno** [comment]
According to FEA calcs, a 40N (~9+lbf) load on the hinge nub will displace it the necessary 1mm to insert into the battery cover.  
![capture2](https://cloud.githubusercontent.com/assets/352025/5886925/d659afb4-a3f0-11e4-84e4-d9c50af1adec.PNG)

At that point the largest stress point is indicated in below in red, and is only half the yield strength of ABS.  So it looks pretty close to what we would want.
![capture](https://cloud.githubusercontent.com/assets/352025/5886914/99b31bb8-a3f0-11e4-8961-622cad7a5dbe.PNG)
