### ISSUE TITLE
Top panel orientation key

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#67]
Right now the top panel is capable of being inserted in any of four orientations. We can add a small key onto the top panel and a keyway into the enclosure to ensure it can be inserted in only one orientation. This would not compromise the ability to use a 1.6 mm PCB as a top panel.

The notch would go on the front side or back side based on assembly order.

It could look something like this.
![screen shot 2015-01-27 at 05 41 43](https://cloud.githubusercontent.com/assets/281642/5908986/377e48ac-a5e7-11e4-838b-625bc7de823b.png)

**Comment by starno** [comment]
good call.  added two small locators on edge of top 

![capture7](https://cloud.githubusercontent.com/assets/352025/5995844/ac2b407a-aad7-11e4-8c5b-3eddd7e07121.PNG)

**Comment by charlespax** [comment]
The top panel can be inserted the wrong way. I'd have to check the SLA print, but I believe the enclosure cannot be screwed shut if it is wrong. Not a huge problem, but a worker would have to correct the mistake. We can avoid them making a mistake entirely if we add a single keyway to the center on the other side.
![Uploading ac2b407a-aad7-11e4-8c5b-3eddd7e07121.png . . .]()
Reopening issue and moving to Enclosure version 0.4 (SLA).

**Comment by starno** [comment]
fixed. 

![capture6](https://cloud.githubusercontent.com/assets/352025/6745870/f9b6e08e-cef8-11e4-9105-d5890e76d720.PNG)
