### ISSUE TITLE
Tilting bail underside support

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#70]
We need to make the battery cover such that the bail can snap without being in the enclosure back.

**Comment by starno** [comment]
underside support is looking nice.  there is now a little interference when the bail is locked open.  things  should feel more robust

![capture3](https://cloud.githubusercontent.com/assets/352025/5995863/eb7c4170-aad7-11e4-9036-db5ad60afc9a.PNG)
