### ISSUE TITLE
Gap around enclosure

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#71]
There is very little gap around the enclosure. This is the gap around the outside separating the front and back.

**Comment by starno** [comment]
@charlespax This really hasn't changed from previous prototypes.  The gap there is 0.25mm, what would you like it to be?

![capture](https://cloud.githubusercontent.com/assets/352025/5991126/c08fc5b8-aa14-11e4-875f-17a2864de1e0.PNG)

**Comment by charlespax** [comment]
To make a decision on this I will look at a few devices to get a sense of what looks good. I'll post my response here.

**Comment by charlespax** [comment]
Woops! I didn't get to this in time. Moving to Enclosure version 0.4 (SLA).

**Comment by charlespax** [comment]
Let's do 0.25 mm in the next SLA print and see how it looks.

**Comment by starno** [comment]
@charlespax that means it will go unchanged.  should I close this issue?
