### ISSUE TITLE
Top panel gap

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#72]
Should we have a gap just like the outer edge (https://github.com/PaxInstruments/t400-enclosure/issues/71)?

**Comment by starno** [comment]
I think both gaps should match

**Comment by charlespax** [comment]
I agree. In the next version whatever we pick for the gap around the enclosure (https://github.com/PaxInstruments/t400-enclosure/issues/71#issuecomment-72352186) we should have for the panel.

**Comment by charlespax** [comment]
Woops! I didn't get to this in time. Moving to Enclosure version 0.4 (SLA).

**Comment by charlespax** [comment]
Looking at a few devices I thin 0.25 mm will be good. Let's to that and see what we get in the next SLA print.

**Comment by charlespax** [comment]
Looks fine to me. Can we close this?

![screen shot 2015-03-19 at 19 56 17](https://cloud.githubusercontent.com/assets/281642/6729898/06d11992-ce72-11e4-8f8d-f6930aca5738.png)

**Comment by starno** [comment]
yep.  its at 0.25mm as desired
