### ISSUE TITLE
Thermocouple number size

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#73]
Should the numbers on the top panel be larger?

**Comment by starno** [comment]
Numbers went from size 16 to 22.  here is a comparison

![capture5](https://cloud.githubusercontent.com/assets/352025/5995878/15540f96-aad8-11e4-95ba-d794902925cf.PNG)

![capture6](https://cloud.githubusercontent.com/assets/352025/5995879/16bcd660-aad8-11e4-9e6b-bcb57e33063b.PNG)

I think it's better, what do you think?

**Comment by charlespax** [comment]
NIce.
