### ISSUE TITLE
Battery cover thickness

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#75]
If make the battery cover thinner, can we make the enclosure thinner by the same amount?

**Comment by starno** [comment]
Yes we can but this is a pretty big change that involves more than one part.  I am hesitant to mess with the nominal thickness of one of the most complex and important pieces of the enclosure.  I don't think the 0.5mm gain is worth the hassle.

**Comment by charlespax** [comment]
Cool. I'm moving this to Enclosure version :-)

**Comment by charlespax** [comment]
Will not do. Closing issue.
