### ISSUE TITLE
PCB standoff

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#76]
We have shoulders on the rear enclosure standoffs (https://github.com/PaxInstruments/t400-enclosure/issues/64). For assembly it would be better to have these on the front panel. However the rear standoff width would be too small to capture the PCB.

Can we put the shoulder on the front panel and make the read panel standoff wider?

**Comment by starno** [comment]
This is also overridden by going in the direction of issue #80
