### ISSUE TITLE
LCD constraint

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#77]
In Enclosure version 0.2 (SLA) the LCD is not constrained fully. There is a little less than a milimeter left to right and about 1.5 mm top to bottom. The LCD/PCB placement is perfect when the LCD is mated with the bottom constrain ribs.

If we get the LCD constrained well, the PCB will be in the right spot and which side the standoff shoulders are on won't matter (https://github.com/PaxInstruments/t400-enclosure/issues/76).

I think we should have something at the top constraining the LCD. We can't move the wall down as that would affect the top panel thickness. We can not make the wall thicker (I think) due to injection molding design constraints causing sink marks. We could probably add two or more ribs as we have at the bottom of the LCD.

If we add ribs, we would have to make the appropriate cutouts in the window panel.

**Comment by starno** [comment]
I think this gets overridden based on our discussion with issue #80 being a cleaner approach.  @charlespax can you confirm?  If so, I will close

**Comment by charlespax** [comment]
I agree. Closing issue.
