### ISSUE TITLE
SD card slot intererence

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#79]
In Enclosure version 0.2 (SLA) the SD card slot does not match up with the enclosure. The card slot also interferes with the enclosure.

**Comment by starno** [comment]
There is definitely some discrepancy here between the CAD and the prototype board.  The connector on the prototype measures a 1.3mm overhang from the pcb edge, when it should be 0.7mm.  (discussed in issue #53)
![capture](https://cloud.githubusercontent.com/assets/352025/5991201/6022b9c4-aa19-11e4-900c-462dae04a859.PNG)
@samchoy88 @charlespax can you verify the overhang of the SD connector on the PCB is 0.7mm and the distance from the edge of the pcb to the centerline of the SD connector is 23.51mm?  
![73e6a9ce-8daa-11e4-9cea-0ed48d23be95](https://cloud.githubusercontent.com/assets/352025/5991209/15e3a6ba-aa1a-11e4-9e4a-1b3a26d22179.png)
If it is easier for me to shift the opening on the enclosure, I can do that too.  Let me know

**Comment by charlespax** [comment]
In eagle I get 1.45 mm overhang. Opened issue  https://github.com/PaxInstruments/t400-electronics/issues/144

![screen shot 2015-02-01 at 14 01 35](https://cloud.githubusercontent.com/assets/281642/5991226/f20e10b2-aa1a-11e4-96b6-e102e49f3527.png)

**Comment by starno** [comment]
Please check the the distance from the side of the PCB as well since the alignment with the opening looks to be around 1mm off

**Comment by charlespax** [comment]
Here you go.

![screen shot 2015-02-01 at 14 19 30](https://cloud.githubusercontent.com/assets/281642/5991267/5f23084a-aa1d-11e4-91a8-6c849361cec9.png)

**Comment by starno** [comment]
Ok, that looks correct.  I must have the SD placement within the connector modeled wrong

**Comment by starno** [comment]
Yup, that was it, and explains the shifted hole in the enclosure.  I had the SD card 0.2mm from the left edge of the connector when looking at its opening.  In the physical connector, this measures to be 1mm.  This was the missing information I mentioned https://github.com/PaxInstruments/t400-electronics/issues/79#issuecomment-68165430   The opening on the enclosure is based on the location of SD card and not the connector location, so it explains the shift.  If https://github.com/PaxInstruments/t400-electronics/issues/145 exposes some other dimensions that are off between the library component and the one we are working with, then we can reopen this issue.
