### ISSUE TITLE
Logo style

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#83]
I think the logo on the enclosure is a bit weak with just the P-microscope. I'd like to try the logo with the circle and with the rounded square as seen in the images below. The outer shape would be an extrude cut into the enclosure. The P-microsope would be an extrude from the bottom of the extrude cut to the surface of the enclosure.

![screen shot 2015-03-01 at 12 29 09](https://cloud.githubusercontent.com/assets/281642/6431969/4ca4831c-c00f-11e4-9343-252a732e2076.png)

**Comment by charlespax** [comment]
I've added Adobe Illustrator files to the repo.

**Comment by starno** [comment]
First impressions is the rounded square will match the shape of what we got already.  I will post a comparrison

**Comment by starno** [comment]
Hmm, here is a quick comparrison of the two:
![capture2](https://cloud.githubusercontent.com/assets/352025/6551205/95a20038-c66f-11e4-8dbb-5c15597250c0.PNG)
![capture3](https://cloud.githubusercontent.com/assets/352025/6551206/9640dfa0-c66f-11e4-9283-e9cdb9449956.PNG)
I'm not so sure I like the border there because the logo needs to get much smaller to keep the same margin proportions.  My personal preference would be to emboss the logo there and maybe add some color to make it pop.  @charlespax what do you think?

**Comment by starno** [comment]
Something kinda like this: 
![capture2](https://cloud.githubusercontent.com/assets/352025/6551462/d5206d86-c673-11e4-8ef6-0bc87936b3e4.PNG)

**Comment by charlespax** [comment]
I agree with you. I guess we're down to two choices: colored logo on the enclosure or logo moved from enclosure to the front label. Do you have a string opinion either way?

**Comment by charlespax** [comment]
If the logo were in the label, it would be smaller than a label embossed on the enclosure.

**Comment by MLXXXp** [comment]
I don't know if you even care, but if the logo is on a stick-on label it makes it easier to OEM the product with a different brand. Embossing the enclosure makes it's more difficult to change. It's also easier if you decide to change your own company logo in the future.

You could also consider just adding a separate larger indent specifically for a logo sticker.

**Comment by charlespax** [comment]
@MLXXXp I agree. We've discussed this before and I think that's a fairly compelling reason. Combined with my desire for flexibility, we should kill the embossed logo and add it to the front sticker.

@starno Let's kill the enclosure logo and move it to the sticker.

**Comment by charlespax** [comment]
I just did a git pull and opened the file. The logo is still there for me. Am I missing something?
![screen shot 2015-03-19 at 17 16 50](https://cloud.githubusercontent.com/assets/281642/6727294/c9696e12-ce5b-11e4-8f67-47081760f7d0.png)

**Comment by charlespax** [comment]
My fault. I was looking `master` rather than `starno`.
![screen shot 2015-03-19 at 19 45 49](https://cloud.githubusercontent.com/assets/281642/6729765/ade1bc02-ce70-11e4-8e5c-04dc86213c56.png)

Looks done. Closing issue.
