### ISSUE TITLE
Add rib to snap wings

### ISSUE THREAD

**Issue by starno** [PaxInstruments/t400-enclosure#84]
The snaps are a bit weak at the base and showing some stress marks.  a small rib reinforcement should help here

![capture](https://cloud.githubusercontent.com/assets/352025/6550408/0747ebac-c662-11e4-8a18-a9cdd0f91d02.PNG)

**Comment by charlespax** [comment]
With the other strength changes do you think you need to do this?

**Comment by starno** [comment]
I think we can hold off on it.  Like you mentioned the snaps on the bail got a lot longer and stronger, so we can hold off unless it's needed again.

![capture3](https://cloud.githubusercontent.com/assets/352025/6744925/48c6e3b8-ceea-11e4-9acf-f42141030132.PNG)

**Comment by charlespax** [comment]
Okay. Moving this to ice box. If it's not a problem with the next prototype, we should close it.

**Comment by charlespax** [comment]
Moving to 0.6 as something we should test when we get the prototypes back.

**Comment by charlespax** [comment]
Added to the review checklist. Closing issue. We can reopen if necessary after test.
