### ISSUE TITLE
Shallower angle on the snap wings

### ISSUE THREAD

**Issue by starno** [PaxInstruments/t400-enclosure#85]
extending the snaps to span further along the edge of the bail can both strengthen the bail and wings

![capture2](https://cloud.githubusercontent.com/assets/352025/6550549/69c3ca00-c665-11e4-8720-867d7d694e02.PNG)

**Comment by charlespax** [comment]
Since you're having trouble with batter interference with that design maybe this a viable option:
![screen shot 2015-03-18 at 13 17 47](https://cloud.githubusercontent.com/assets/281642/6703182/7f3d1a44-cd72-11e4-9943-409fba47252a.png)

I don't think this interferes with anything.

**Comment by charlespax** [comment]
Can we close this?

**Comment by starno** [comment]
yeah, bail got a lot stronger

![capture5](https://cloud.githubusercontent.com/assets/352025/6745490/79e53992-cef2-11e4-91e7-807795dd686c.PNG)
