### ISSUE TITLE
Further tighten bail clearance inside cover

### ISSUE THREAD

**Issue by starno** [PaxInstruments/t400-enclosure#86]
There is still too much wiggle room allowing it to slide back and forth when jostled

**Comment by charlespax** [comment]
Looks good in the model. Can we close this?

**Comment by starno** [comment]
@charlespax Im tempted to add in some bulbous features on the inside edge of the bail to give it a point contact with the battery cover and have minimal friction when opening.  The clearance between the two parts is tighter than the last prototype, but I'm starting to think something along these lines is the only way to eliminate it.  What are your thoughts?

![capture3](https://cloud.githubusercontent.com/assets/352025/6744810/f8b3c996-cee8-11e4-83f0-5a200455c35d.PNG)

**Comment by charlespax** [comment]
That makes sense. Maybe put them on the most flexible parts of the tilting bail.

![f8b3c996-cee8-11e4-83f0-5a200455c35d](https://cloud.githubusercontent.com/assets/281642/6745630/b91d557a-cef4-11e4-8863-8142e671629e.png)

**Comment by starno** [comment]
moving this to the production unit milestone.  Depending on how 0.4 comes out, this is something to iron out with tooling and make sure things are cut short so we can always add a bit of material until the fit is right.

**Comment by charlespax** [comment]
Moved to milestone 0.5. The tooling milestone is only for things relevant to the tooling.

**Comment by charlespax** [comment]
Okay, let's see if this problem comes up again in the next prototypes. If so, we can file a new issue. Closing issue.
