### ISSUE TITLE
Keep snaps from escaping battery cover's grasp

### ISSUE THREAD

**Issue by starno** [PaxInstruments/t400-enclosure#87]
Currently the bail "locks" open when the snaps pop out of the battery cover and sit in an open pocket.  
![capture](https://cloud.githubusercontent.com/assets/352025/6550984/f98be392-c66b-11e4-8775-2df35066a299.PNG)
The prototype is difficult to "unlock" from this position when closing the bail, however it is very easy to open back up again.  Therefore, the bail hinge needs to sit a little deeper inside the battery cover to prevent the snaps from ever becoming totally free.

**Comment by charlespax** [comment]
Looks about right in the model. Can we close this?

**Comment by starno** [comment]
Yeah, bail snaps managed to get longer, the locking positions moved toward the top, and the open locking position is recessed to prevent over extension.

![capture3](https://cloud.githubusercontent.com/assets/352025/6744741/f309a21e-cee7-11e4-81a7-94f83a03efd9.PNG)
