### ISSUE TITLE
Battery cover chamfer

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#90]
Should the edge of the battery cover be chamfered?

![screen shot 2015-03-19 at 20 08 35](https://cloud.githubusercontent.com/assets/281642/6730073/c3baf180-ce73-11e4-98f8-b1fe400ab394.png)

**Comment by starno** [comment]
this was taken care of in 8a57f50cb0572b26ae022d37b2a37487b056f935
