### ISSUE TITLE
Tilting bail chamfer weirdness

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#91]
This highlighted bit is a little weird. Does that matter?

![screen shot 2015-03-19 at 20 10 20](https://cloud.githubusercontent.com/assets/281642/6730091/03fe07a0-ce74-11e4-8f24-2135ec28e790.png)

**Comment by starno** [comment]
good catch, resolved.

![capture6](https://cloud.githubusercontent.com/assets/352025/6745090/08e08490-ceed-11e4-9cc0-0314cdde8328.PNG)
