### ISSUE TITLE
Silicone keypad graphics

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#92]
@paxmanchris is taking care of the silicone keypad graphics.

The graphics can be found in the manual https://github.com/PaxInstruments/t400-electronics/blob/master/documentation/manual.md

Here are the dimensions we are working with.
![screen shot 2015-03-23 at 14 48 07](https://cloud.githubusercontent.com/assets/281642/6775408/c0d00618-d16b-11e4-9c8a-0b142292cb08.png)

A key here is to make a reusable interface if possible, so we can use this on other devices or people to use in their own projects.

Please add the graphics to a sub folder in https://github.com/PaxInstruments/t400-enclosure/tree/master/graphics

**Comment by paxmanchris** [comment]
Here is a draft for the cycle icon
![cycle](https://cloud.githubusercontent.com/assets/8140248/6776300/b406e530-d177-11e4-98c4-fea060e72fd6.png)

**Comment by charlespax** [comment]
![enclosure-front-buttons](https://cloud.githubusercontent.com/assets/281642/6777820/3b9e3614-d188-11e4-9a34-6c67a5bbd69f.png)

Cycle channels
![cycle_icon](https://cloud.githubusercontent.com/assets/281642/6777833/54b0f75e-d188-11e4-8335-3aef13185b5b.png)

Backlight 
![brightness_icon](https://cloud.githubusercontent.com/assets/281642/6777823/44f7147e-d188-11e4-8b1f-fe5d47b63cc2.png)

Power
![Uploading power_icon.png . . .]()

Logging start/stop
![logging_icon](https://cloud.githubusercontent.com/assets/281642/6777839/66a2a1d8-d188-11e4-9d51-d09b83ece589.png)

Log interval
![screen shot 2015-03-23 at 18 14 42](https://cloud.githubusercontent.com/assets/281642/6777847/8313b10e-d188-11e4-86e3-b87a89a96038.png)

Units: Unknown

**Comment by paxmanchris** [comment]
Okay, I [uploaded the design](https://github.com/PaxInstruments/t400-enclosure/blob/master/graphics/buttons_worksheet.svg), staying as close to what was described in the [documentation](https://github.com/PaxInstruments/t400-electronics/blob/master/documentation/manual.md#buttons). Here is a picture what I have done so far:

![buttons_export](https://cloud.githubusercontent.com/assets/8140248/6777777/bc76efc0-d187-11e4-84e2-5b1e721f167a.png)

@charlespax take a look and let me know if it needs to be tweaked.

**Comment by charlespax** [comment]
Check out https://useiconic.com/open#icons, a bunch of free icons on github https://github.com/iconic/open-iconic.

**Comment by paxmanchris** [comment]
Interesting but, I don't see any that fit what you want. Here is a mock up of the front panel with logos:

![front_panel_with_logos](https://cloud.githubusercontent.com/assets/8140248/6778203/a8ac1534-d18b-11e4-9081-4addf23ddbb4.png)

**Comment by charlespax** [comment]
Icons from Google https://github.com/google/material-design-icons/releases/tag/1.0.0

Cycle channels: ![screen shot 2015-03-23 at 18 46 14](https://cloud.githubusercontent.com/assets/281642/6778387/4aaeb192-d18d-11e4-8fa4-8aa10e8b24bc.png)
Backlight: 
Power: ![screen shot 2015-03-23 at 18 47 19](https://cloud.githubusercontent.com/assets/281642/6778363/13988908-d18d-11e4-8f59-4d6c7aa8ba49.png)
Start/stop: 
Interval: ![screen shot 2015-03-23 at 18 46 42](https://cloud.githubusercontent.com/assets/281642/6778378/3d6b5d8c-d18d-11e4-9ab6-8d0328c68c73.png) or ![screen shot 2015-03-23 at 18 47 01](https://cloud.githubusercontent.com/assets/281642/6778384/443305ac-d18d-11e4-960a-aafde187a351.png)

Units:

**Comment by charlespax** [comment]
There is also stuff form Font Awesome http://fortawesome.github.io/Font-Awesome/icons/

**Comment by charlespax** [comment]
Here's a mockup on the SLA prototype.
![img_20150325_145139](https://cloud.githubusercontent.com/assets/281642/6819615/f3f752d2-d2fe-11e4-8fdd-6fc692dcae1c.jpg)

**Comment by paxmanchris** [comment]
Okay. Here is what I have so far:
![front_panel_with_logos2](https://cloud.githubusercontent.com/assets/8140248/6820524/1262bb9c-d30b-11e4-9aad-2549f6f9b2c4.png)

**Comment by charlespax** [comment]
Changes:

- Make the record circle the same size as the power button circle
- Make the temperature units button read "**°CFK**" or "**CFK**" in a single line. Do NOT do KFC :-)
- Make the delta t a little smaller. I don't know why, but it just looks really big

**Comment by charlespax** [comment]
Here's a mockup with a smaller record button and a clock.
![1262bb9c-d30b-11e4-9aad-2549f6f9b2c4 copy](https://cloud.githubusercontent.com/assets/281642/6821463/04195328-d312-11e4-87a0-d0dba40669ab.png)

**Comment by charlespax** [comment]
Empty thermometer
![1262bb9c-d30b-11e4-9aad-2549f6f9b2c4 copy 2](https://cloud.githubusercontent.com/assets/281642/6821884/7cbaa530-d316-11e4-9e8c-74a46a8acbed.png)

Filled thermometer.
![1262bb9c-d30b-11e4-9aad-2549f6f9b2c4 copy 2](https://cloud.githubusercontent.com/assets/281642/6821873/6218f042-d316-11e4-8f0f-97085c483b8f.png)

**Comment by charlespax** [comment]
Here's an updated screenshot
![screen shot 2015-03-25 at 18 06 39](https://cloud.githubusercontent.com/assets/281642/6822314/c02dc038-d319-11e4-84ff-2daa51712d50.png)

**Comment by paxmanchris** [comment]
After discussing about it, here the interface with a half filled thermometer and graph without arrow.
![front_panel_with_logos3](https://cloud.githubusercontent.com/assets/8140248/6823431/eeb74aec-d322-11e4-97b2-aba272d65c44.png)

**Comment by charlespax** [comment]
Perfect!

**Comment by paxmanchris** [comment]
I added a [pdf](https://github.com/PaxInstruments/t400-enclosure/blob/master/graphics/button_label_measurement_specifications.pdf) that lays out the button placement. All the buttons are separated into svg's and exorted as 600dpi png files,  [all in the repository](https://github.com/PaxInstruments/t400-enclosure/blob/master/graphics/button_label_measurement_specifications.pdf) . If the pdf looks good please close.

**Comment by charlespax** [comment]
Use drawings with the white background. For each image, indicate the size of the image bounding box, not the distance to the edge. That will be much easier to measure.

**Comment by paxmanchris** [comment]
I could not find the pdf of the white background for the buttons. Could you put the asset in the repo?

**Comment by charlespax** [comment]
Here you go.

![screen shot 2015-04-04 at 18 14 26](https://cloud.githubusercontent.com/assets/281642/6992264/806a5184-daf6-11e4-9a56-979c9aab7d40.png)

**Comment by paxmanchris** [comment]
I updated the  [pdf](https://github.com/PaxInstruments/t400-enclosure/blob/master/graphics/button_label_measurement_specifications.pdf).

**Comment by charlespax** [comment]
I think there is a problem. The clock and record icons are circles, but the document shows different height and widths for each.

**Comment by paxmanchris** [comment]
I committed some the changes you requested. I know the backlight is still off, but if made square the center circle looks distorted. Please add updated buttons layout when you can

**Comment by charlespax** [comment]
Post a screenshot.

**Comment by charlespax** [comment]
I've uploaded the new keypad drawing in PDF PNG and DXF (vector) formats. Here is the PNG.
![t400-silicone-buttons-right-assembly](https://cloud.githubusercontent.com/assets/281642/6996397/6f98ffb4-dbb8-11e4-989f-0cfdb5f5ff88.png)

**Comment by paxmanchris** [comment]
Here is the comparison:
![screen shot 2015-04-05 at 6 01 01 pm](https://cloud.githubusercontent.com/assets/8140248/6996484/cd6cc2d8-dbbd-11e4-98e8-d97a557213da.png)

Very minor. if you can tell me which is which then fine. Might make just to square it anyways.

**Comment by charlespax** [comment]
I mean post a screenshot the same as I did with my feedback. I want to see what it looks like.

**Comment by paxmanchris** [comment]
I think your right, and we should have the dimensions square.
![screen shot 2015-04-06 at 2 10 29 pm](https://cloud.githubusercontent.com/assets/8140248/7001217/c0ba6190-dc66-11e4-9388-72e731ca370e.png)

**Comment by charlespax** [comment]
Now the power button is messed up.

**Comment by charlespax** [comment]
@paxmanchris what's the status of this?

**Comment by paxmanchris** [comment]
This is done. we got the buttons :smile:
