### ISSUE TITLE
Front panel graphics

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#93]
@paxmanchris is taking care of the front panel graphics.

The graphics can be found in https://github.com/PaxInstruments/t400-enclosure/tree/master/graphics. Let me know if you need any other graphics to get this done.

Here are the dimensions we are working with.
![screen shot 2015-03-23 at 14 48 07](https://cloud.githubusercontent.com/assets/281642/6775408/c0d00618-d16b-11e4-9c8a-0b142292cb08.png)

**Comment by paxmanchris** [comment]
@charlespax  What do you think of these?

![labels_example](https://cloud.githubusercontent.com/assets/8140248/6779137/e8e35308-d193-11e4-980c-76a6b7e6ccb6.png)

**Comment by paxmanchris** [comment]
See also [label_worksheet.svg](https://github.com/PaxInstruments/t400-enclosure/blob/master/graphics/label_worksheet.svg)

**Comment by charlespax** [comment]
I think using the square or circle around the logo makes the microscope logo too small. We also end up with a ton of empty space. I think something like this would solve those two problems.
![b25b4d9e-d194-11e4-9891-ebf59d3e621d](https://cloud.githubusercontent.com/assets/281642/6779374/5b2226a4-d196-11e4-80ac-06d5176b0512.png)

It also has the Pax Instruments name, which is nice. I think that will help with brand recognition. The microscope logo would be bigger than using the enclosed version.

**Comment by MLXXXp** [comment]
Is it just going to say **T400**? With all that space, why not include the function of the device, such as **T400 Thermocouple Datalogger.**

When I pick up a new device for the first time, I find it nice to be able to find some indication of its purpose.

**Comment by charlespax** [comment]
I think we should have "Pax Instruments on it" to help develop the brand. I do agree though, it would be nice to say what the device does.

**Comment by charlespax** [comment]
Maybe if we just use "Pax" we can add "temperature datalogger"
![b25b4d9e-d194-11e4-9891-ebf59d3e621d copy 2](https://cloud.githubusercontent.com/assets/281642/6779538/ff66c318-d197-11e4-823d-596c50a56f6e.png)

**Comment by charlespax** [comment]
Here is the type of label we'll have.
![img_20150323_115907](https://cloud.githubusercontent.com/assets/281642/6779673/80a31e12-d199-11e4-9a94-49bb87ac8b72.jpg)

The label on this Rigol scope has the same 7.8 mm height as the T400 label. The calipers mark off the length we have to work with on the T400.
![img_20150323_201319](https://cloud.githubusercontent.com/assets/281642/6779702/bb0de316-d199-11e4-980c-190ff29a697e.jpg)

**Comment by paxmanchris** [comment]
Okay, thanks for the input. Based on what you wrote, I added "temperature datalogger" to the label, and made a few designs with it:
![labels_example2](https://cloud.githubusercontent.com/assets/8140248/6782088/f4ff6280-d1ac-11e4-8071-b39ab9c47c07.png)

**Comment by charlespax** [comment]
Nice. That's starting to look pretty tight. I like how you have things divided. I think we'll have to print some of these and see how they look.

Here's another option:
![screen shot 2015-03-23 at 23 05 22](https://cloud.githubusercontent.com/assets/281642/6782769/1de19f98-d1b1-11e4-925d-fc6e0a3c8815.png)

**Comment by paxmanchris** [comment]
Okay, revision 3. In the examples below:
1. blue, white, on black with white on gray for model number
2.  blue, black on white with  white on gray for model number
3.  blue, black on white

4, 5, 6 are the same only that "Pax" is clear.

![labels_example3](https://cloud.githubusercontent.com/assets/8140248/6796333/40fb7726-d22c-11e4-8e4a-3a40dc187cfe.png)

**Comment by paxmanchris** [comment]
@starno @MLXXXp  any thoughts on the revision?

**Comment by charlespax** [comment]
What about something like this? Can you mock this up quickly?

![img_20150324_150849](https://cloud.githubusercontent.com/assets/281642/6798728/fbc80920-d24a-11e4-9b89-a51ac1c7c495.jpg)

**Comment by paxmanchris** [comment]
Okay, here:

![labels_example4](https://cloud.githubusercontent.com/assets/8140248/6801204/c721c10a-d260-11e4-83ca-2fd76b67922b.png)

**Comment by MLXXXp** [comment]
How about 3 (blue, black on white) but with **Temperature Datalogger" in blue?

**Comment by paxmanchris** [comment]
I think it does not stand out well for blue **Temperature Datalogger**

![labels_example6](https://cloud.githubusercontent.com/assets/8140248/6801566/e1b9753c-d263-11e4-96cd-3bc70cce6032.png)

**Comment by paxmanchris** [comment]
Quick mockup of the bevel going the other way:

![labels_example7](https://cloud.githubusercontent.com/assets/8140248/6801831/34911d3a-d266-11e4-911b-d48c1eea58c6.png)

**Comment by charlespax** [comment]
Of the layered design I like this the best. However, the layering seems a bit cluttered.
![screen shot 2015-03-24 at 20 44 16](https://cloud.githubusercontent.com/assets/281642/6801908/9dc1fe8c-d266-11e4-99cc-5a2789c8283c.png)

Having just the T400 blocked off looks pretty good.
![screen shot 2015-03-24 at 20 45 55](https://cloud.githubusercontent.com/assets/281642/6801925/e2abee22-d266-11e4-8bf9-51b8380381ac.png)

I also really like the simple style of this one.
![screen shot 2015-03-24 at 20 44 20](https://cloud.githubusercontent.com/assets/281642/6801933/f24f2542-d266-11e4-8741-eca300461576.png)

**Comment by MLXXXp** [comment]
**paxmanchris** wrote:
> I think it does not stand out well for blue **Temperature Datalogger**

Then I think you'd have to say that **Pax** doesn't stand out well either.

**Comment by paxmanchris** [comment]
Some variations one the one we like:
![labels_example7](https://cloud.githubusercontent.com/assets/8140248/6807874/232a6d64-d28c-11e4-873c-17e6a4b71671.png)


1. original from last post 
2. larger temperature datalogger
3. cleaned up, the right edge of t400 and the inner edge of the I in the P are the same distance from the outer edge (about 2mm).
4. The P looked a little to close to top, so I centered it. But now the bottom T400 is no longer flush with the brand (it did not loot right with with T400 uncentered). Yet I still like this one.

Here is with the T400 flush with the logo if moved down:
![screen shot 2015-03-25 at 1 24 18 am](https://cloud.githubusercontent.com/assets/8140248/6808313/53a600fa-d28e-11e4-9490-fd5f40722401.png)

**Comment by MLXXXp** [comment]
Number 4 and the last one have too much white above and not enough below. It doesn't look vertically centred and gives the impression of wasted space, especially from a distance.

I prefer number 3. The top of the **P** being close to the top edge doesn't seem too bad to me. **Temperature Datalogger** could maybe be slightly larger, though not a big as number 2.

**Comment by MLXXXp** [comment]
I don't know if the **PAX** logo is cast in stone but I'd consider making the **AX** larger. Right now, there could be a slight chance that some people might ignore the microscope and arm part of the **P** and see **IAX**. **INSTRUMENTS** could remain as it is, thus becoming slightly smaller overall.

**Comment by charlespax** [comment]
"Temperature Datalogger" should be black. The color blue is reserved for the Pax Instruments logo and things that enhance our brand, like the enclosure color.
![screen shot 2015-03-25 at 08 43 04](https://cloud.githubusercontent.com/assets/281642/6816238/571e5362-d2cb-11e4-935d-c03c7416659b.png)

Other than the microscope being too close to the top, this one does look well balanced. I like that the bottom edges of the text are aligned.
![screen shot 2015-03-25 at 08 48 15](https://cloud.githubusercontent.com/assets/281642/6816267/c5123082-d2cb-11e4-9a0c-521cc03b4d51.png)

This one does seem a bit too low. It looks strange without the alignment.
![screen shot 2015-03-25 at 08 48 20](https://cloud.githubusercontent.com/assets/281642/6816271/ce02bc70-d2cb-11e4-9f5b-a9bd473d4138.png)

I think the last one looks best.
![53a600fa-d28e-11e4-9490-fd5f40722401](https://cloud.githubusercontent.com/assets/281642/6816308/6cc7a0b4-d2cc-11e4-994b-c945fd5f6355.png)

I did a rough edit to the image below. The microscope is a touch closer to the top than to the bottom, but not as close as before. "Temperature Datalogger" and "T400" are a touch larger, which I feel is too large.
![53a600fa-d28e-11e4-9490-fd5f40722401](https://cloud.githubusercontent.com/assets/281642/6816404/ce997a28-d2cd-11e4-899a-f01fa472b4ee.png)

@MLXXXp can you make some mockups of what you think would look good? The graphics assets can be found at https://github.com/PaxInstruments/t400-enclosure/tree/master/graphics

**Comment by MLXXXp** [comment]
Now that I've seen **Temperature Datalogger** in a larger font, I'd have to say I prefer the original size.

As I've said, I don't see the **P** being close the the top as being a problem, so I like the vertical balance of the second one above. I took that one and moved the **T400** so it's closer to the same distance from the right edge as **PAX** is from the left. I also moved **Temperature Datalogger** slightly to make it look centered.

![pax_sticker1](https://cloud.githubusercontent.com/assets/8151717/6817386/23e4a03c-d276-11e4-804a-1317619292e4.png)

Have you considered switching the model and description? I'm not sure which I prefer.

![pax_sticker2](https://cloud.githubusercontent.com/assets/8151717/6817525/fa30e0a0-d277-11e4-87d6-93ad3ba8f0f9.png)

**Comment by charlespax** [comment]
Both of those look good. The T400 on the right visually appeals to me a bit more. However, I think the T400 in the middle reads better: "Pax Instruments T400 temperature datalogger" is how I've been talking about he device. Let's go with the second option.

@paxmanchris upload an SVG with 600 dpi PNG and JPG files. I also need a PDF indicating the dimensions of the label. Let's take the label in 0.3 mm, so we'll have 72 mm x 7.5 mm.

**Comment by charlespax** [comment]
I've ordered labels. Closing issue. We can make a new issue if there is a problem.
