### ISSUE TITLE
Top panel recess

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#95]
Cross posted from https://github.com/PaxInstruments/t400-electronics/issues/17

There may be a problem with how deep the connector inserts into the T400.

Here is the current connector version.
![screen shot 2015-03-24 at 20 17 52](https://cloud.githubusercontent.com/assets/281642/6802194/3f3abdba-d269-11e4-898d-1259aef41ba7.png)

The thermocouple would have to go a minimum of 5.7 mm into the connector to make contact. The shortest thermocouple connector I've seen is about 10 mm. Those numbers work well if the male part is fully inserted into the female part.
![screen shot 2015-03-24 at 20 18 54](https://cloud.githubusercontent.com/assets/281642/6802195/4162bdae-d269-11e4-9a38-c3bb5efe07d6.png)
![img_20150324_202229](https://cloud.githubusercontent.com/assets/281642/6802322/64d82e8a-d26a-11e4-8bd7-2adbc9487fc8.jpg)

For the T400 a male thermocouple connector must pass through the enclosure and a gap before it inserts into the female connector. In this image the black line marks off the point of contact.
![img_20150324_202212](https://cloud.githubusercontent.com/assets/281642/6802298/327aca4c-d26a-11e4-9eb1-d9100eba10c7.jpg)

We could have an indentation in the top panel, so the male connectors would only have to pass through the thickness of the enclosure. That would get the job done, but isn't the best contact and may not be very secure.
![img_20150324_202302](https://cloud.githubusercontent.com/assets/281642/6802345/991dd528-d26a-11e4-933c-70e29061ea5d.jpg)

We could remove the tab from the entrance of the connector and have two tabs on the sides. This would allow us to hang the connector over the edge and span the gap or part of the gap.
![screen shot 2015-03-24 at 20 54 48](https://cloud.githubusercontent.com/assets/281642/6802391/fe5edf9a-d26a-11e4-953f-4ad62ef41d49.png)
![screen shot 2015-03-24 at 20 54 41](https://cloud.githubusercontent.com/assets/281642/6802392/fe665270-d26a-11e4-9bb8-3881251a266d.png)

This would, however, cause some assembly problems when installing the top panel. I think we could overhang about 1.5 mm without causing problems. Perhaps a combination of wings on the sides and an indentation in the top panel is the solution.

Update: I accidentally removed the flange from the entrance. We would probably have a flange going up and a flange going down to aid thermocouple insertion.

**Comment by starno** [comment]
Are you proposing to make a recess on the top panel to give the connector pins more guaranteed depth inside the mating connector?

**Comment by charlespax** [comment]
Yes

**Comment by charlespax** [comment]
It looks like a recess would be too close to the edge. We would have to make the whole top panel one flat piece. I hope we can address by changing the connector. We could also extend the PCB, but that wouldn't be as clean.

![img_20150325_164817](https://cloud.githubusercontent.com/assets/281642/6820995/f32c890c-d30e-11e4-99d9-89328597b1a9.jpg)

**Comment by starno** [comment]
Here is the current arrangement with the new SMT connectors:

Top panel no longer has channels for the male end of the thermocouple connector, and sits 0.48mm from the inner surface of the top panel:
![capture2](https://cloud.githubusercontent.com/assets/352025/7448676/fb3ebb70-f252-11e4-9611-4bd0ac849135.PNG)

The shortest connector I have is the Chinese knockoff which has 10mm long male contacts.  Approximately 2.5mm of that will be going through the top panel and clearance before the connector, with the remainder inside the connector.  The bottom edge of the inlet also aligns with the bottom edge of the connector, so all the force after insertion will be displacing the spring portion of the connector:
![capture4](https://cloud.githubusercontent.com/assets/352025/7448692/8c10786e-f253-11e4-9aad-80191f93f74e.PNG)

I think this issue can be closed.

**Comment by charlespax** [comment]
I don't see those top panel changes in git hub in either starno or master.

**Comment by starno** [comment]
Hmm, it was part of this commit:
https://github.com/PaxInstruments/t400-enclosure/commit/2cebe68f543333da7238f13286a397d0a8f6d0ea

**Comment by charlespax** [comment]
Oh I see. I have to `git checkout starno` and `git pull` to get the updates. If I'm on `master`, `git pull` does not bring in updates in `starno` and does not tell me that it was updated. I have the changes now. Closing issue.
![screen shot 2015-05-04 at 17 30 35](https://cloud.githubusercontent.com/assets/281642/7451444/49ef7a0e-f283-11e4-8e8a-e2e430d461a8.png)
