### ISSUE TITLE
Button height

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#97]
As we discussed, the button height could be reduced. However, the current height has been growing on me. I'm still not sure what we should do.

![img_20150325_144632](https://cloud.githubusercontent.com/assets/281642/6819573/019b164a-d2fe-11e4-810b-368be9af63f5.jpg)

What do you think of reducing the height on only the power button? This could avoid the device accidentally turning on while stored. Thoughts?

**Comment by starno** [comment]
At the moment I think they are a little too big and a little too easy to accidentally press while holding it.  Slightly recessed power button is interesting idea.  We can probably make it subtle enough that it has the preventative functionality without the user recognizing a difference in height

**Comment by charlespax** [comment]
You have the other buttons of various height. Which do you like best?

**Comment by charlespax** [comment]
You have the other buttons of various height. Which do you like best?

**Comment by starno** [comment]
I think 1.0mm above the enclosure surface feels the best.

**Comment by charlespax** [comment]
I like the feel of 1.0 mm also. Let's go with that.

**Comment by starno** [comment]
1.0mm it is

![capture](https://cloud.githubusercontent.com/assets/352025/9149233/2c915b8a-3dd3-11e5-855e-099037526839.PNG)
