### ISSUE TITLE
SD card slot

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#98]
The bottom edge of the SD card slot should come up some more.

![img_20150325_150311](https://cloud.githubusercontent.com/assets/281642/6819696/3cbb7f74-d300-11e4-9faf-890897011670.jpg)

**Comment by starno** [comment]
done 

The height of the latest sd connector was not updated in the CAD
![capture3](https://cloud.githubusercontent.com/assets/352025/6884371/d4a59526-d621-11e4-947d-9a516ff6ad22.PNG)

should be better now
![capture4](https://cloud.githubusercontent.com/assets/352025/6884367/9a725efc-d621-11e4-8ccd-2bea33b220c9.PNG)
