### ISSUE TITLE
Locating rib height

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#99]
I think we should increase the height of the two PCB locating ribs. In the picture below the T400 is flat against a table and the buttons are installed. Since the buttons normally protrude from the enclosure from surface the button will lift the PCB away from the enclosure resulting in a very small engagement between the locating ribs and the PCB slots. This effect would be reduced if we decrease the button height (https://github.com/PaxInstruments/t400-enclosure/issues/97). Making the ribs taller would improve a workers ability to accurately locate the PCB.

![img_20150325_150827](https://cloud.githubusercontent.com/assets/281642/6819737/fed484b6-d300-11e4-8bcc-f8e9e915f2ca.jpg)

**Comment by starno** [comment]
fully extended height of ribs to meet the front panel outer edge
![capture](https://cloud.githubusercontent.com/assets/352025/6884455/31e3d438-d626-11e4-8e75-5a21cc916940.PNG)
